name: Build and Deploy to ECS

on:
  push:
    branches:
      - main # Change this to your default branch if it's different

jobs:
  # Build and Push to ECR Job
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR Public
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - name: Build the Docker image
        run: |
          docker build -t swiggy-app .

      - name: Tag the Docker image
        run: |
          IMAGE_URI=public.ecr.aws/k7m2z4k7/swiggy-app:latest
          docker tag swiggy-repo $IMAGE_URI

      - name: Push the Docker image to ECR
        run: |
          IMAGE_URI=public.ecr.aws/k7m2z4k7/swiggy-repo:latest
          docker push $IMAGE_URI

      - name: Set IMAGE_URI for deployment
        run: echo "IMAGE_URI=public.ecr.aws/k7m2z4k7/swiggy-app:latest" >> $GITHUB_ENV
